 version: '3'

 services:
   mysql-partner:
     image: mysql:8.0.28
     ports:
       - 3306:3306
     environment:
       - MYSQL_ROOT_PASSWORD=12345678
   partner-backend:
     image: partner-backend:latest
     build: .
     ports:
       - 9002:9002
     depends_on:
       - mysql-partner
